### PR TITLE
Added rules of the game

### PR DESCRIPTION
**Pull request by ghost**
I have added a set of instructions for the game.
image

### CODE REVIEW

**Comment by baidi-mannan** [comment]
@AggiSahithi  Nice Work!
But I want this to appear when we click the play button and it should be in the middle of the screen.

The flow will be
The intro box
Click Play game
A box with the rules at the center of the screen (Adjust the width and Height as your wish)
Add a button of Let's Play in the rules box.
Then the rules box disappear 
And the game starts.
Hope you got it,😅

If yes then please do the changes in the code.
Else, you can ask the doubts here.

**Comment by ghost** [comment]
Is this kind of pop up ok??
image

**Comment by baidi-mannan** [comment]
Yeah!!! Great work 👍 

Just add an Let's Go Button at the bottom of the box and then create a pull request'.

Peace!!

**Comment by baidi-mannan** [comment]
Can you please share a screenshot or video recording of the game?

**Pull request merged**
