### PR TITLE
Image folder and favicon added

### PR DESCRIPTION
**Pull request by astroidworld**
I have added an **Image folder** where the favicon images are present. I have also written a code to add a **favicon**. The image folder contains **five favicon images** so that you can choose what you want.

please check the changes and merge it.
#7 issue solved

### CODE REVIEW

**Comment by baidi-mannan** [comment]
Can I found and image which will be suitable for the game imo.
Here is it's link
https://www.google.com/search?q=divide+logo&rlz=1C1SQJL_enIN910IN910&tbm=isch&source=iu&ictx=1&fir=8ILHNhbpRDlkZM%252CXNQUOqumyjYofM%252C_&vet=1&usg=AI4_-kSXwU8Yw32mYEyRl3-lkG0dJna1-A&sa=X&ved=2ahUKEwiR3_mw5LztAhXhzzgGHVQ_C9sQ9QF6BAgMEAE&cshid=1607375657550011#imgrc=8ILHNhbpRDlkZM

Just change the necessary things and delete all other images. So that, I can merge this in my project.
Peace!!

**Comment by astroidworld** [comment]
I have changed the favicon and deleted all other images from the image folder.

**Comment by astroidworld** [comment]
please check the changes and marge it.

**Comment by baidi-mannan** [comment]
Okay!!

**Pull request merged**
